input {

  file {
    path => "/logs/backend.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "backend"
  }

  file {
    path => "/logs/frontend.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "frontend"
  }

}

filter {
    grok {
      match => {
        "message" => "%{TIMESTAMP_ISO8601:log_timestamp}\s+%{LOGLEVEL:level}"
      }
    }
}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "application-logs"
  }
  
  stdout {
    codec => rubydebug
  }

}