sonar.projectKey=romainsessa_P7_mettez-en-oeuvre-lintegration-et-le-deploiement-continu-dune-application-full-stack
sonar.projectName=P7_mettez-en-oeuvre-lintegration-et-le-deploiement-continu-dune-application-full-stack
sonar.organization=romainsessa-1

sonar.sources=back/src/main,front/src
sonar.tests=back/src/test
sonar.test.inclusions=front/src/**/*.spec.ts

sonar.sourceEncoding=UTF-8

# Java
sonar.java.binaries=back/build/classes

# Angular
sonar.typescript.tsconfigPath=front/tsconfig.json

# Exclusions
sonar.exclusions=**/*.spec.ts, **/node_modules/**, **/dist/**
